services:
  jupyter:
    build: .
    container_name: jupyter_container
    ports:
      - "8888:8888"
    volumes:
      - ./scripts:/estoque-data-bi/scripts
      - ./data:/estoque-data-bi/data
      - ./notebooks:/estoque-data-bi/notebooks
    working_dir: /estoque-data-bi
    # command: bash -c "python extract_data.py"
    networks:
      - docker_network

volumes:  
  mysql_data:

networks:
  docker_network:
    external: true
