version: '3.8'

services:
  python_app:
    image: python:3.11
    container_name: python_app_container
    volumes:
      - ./scripts:/estoque-data-bi/scripts
      - ./data:/estoque-data-bi/data
    working_dir: /estoque-data-bi/scripts
    command: bash -c "pip install -r requirements.txt && python extract_data.py"
    networks:
      - docker_network

  jupyter:
    build: .
    container_name: jupyter_container
    ports:
      - "8888:8888"
    volumes:
      - ./scripts:/estoque-data-bi/scripts
      - ./data:/estoque-data-bi/data
      - ./notebooks:/estoque-data-bi/notebooks
    working_dir: /estoque-data-bi/notebooks
    depends_on:
      - python_app

volumes:  
  mysql_data:

networks:
  docker_network:
    external: true
