version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  python_app:
    image: python:3.11
    container_name: python_app_container
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    working_dir: /scripts
    command: bash -c "pip install -r requirements.txt && python extract_data.py"
    depends_on:
      - mysql

volumes:  
  mysql_data:
